plugins { id 'com.android.application' }

android {
    namespace 'com.example.calculatorbasic'
    compileSdk { version = release(37) }
    defaultConfig {
        applicationId 'com.example.calculatorbasic'
        minSdk 24
        targetSdk 37
        versionCode 2
        versionName '1.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
